import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../component/Navbar";
import Footer from "@/component/Footer";

export const metadata: Metadata = {
  title: "The Cutting Bar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}